baseurl = "https://jfbocoum.netlify.app"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Jacqueline Fatima Bocoum"
theme = "dream"

copyright = "Jacqueline Fatima Bocoum"

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "#f7f7f7"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  # dark mode
  defaultDark = false
  backgroundDark = "black"
  #backgroundImageDark = "/me/background-dark.jpg"
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true

  author = "Jacqueline Fatima Bocoum"
  description = "Dans mon coeur débattent une auteure et une lectrice  sous les yeux d'une cinéphile passionnée qui adore -Dîner de cons-..."
  avatar = "/img/avatar.jpeg"
  headerTitle = "Jacqueline Fatima Bocoum"
  motto = "Écrivain"
  # maxTags = 5
  # categoriesLimitInHeader = 6 # deprecated
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""
  # VALINE_LANGUAGE = ""

  #email = "g1enyy0ung@gmail.com"
  twitter = "fatima_bocoum"
  #facebook = ""
  instagram = "jfbocoum"
  # mastodon = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2021

  # favicon = "/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  # options
  # showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  # reversePostAndAside = true
  # shareInAside = true
  # fixedNav = true
  # collapsibleTags = true
  # collapseBySummary = true

  # [params.advanced]
  #   customCSS = ["css/custom.css"]
  #   customJSBefore = []
  #   customJS = []

  # [params.experimental]
  #   jsDate = true
  #   jsDateFormat = "yyyy年MM月dd日"
